# Generated by Django 5.0.1 on 2026-01-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyanalytics',
            unique_together={('year', 'month')},
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', '-viewed_at'], name='analytics_b_blog_id_09fc43_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['user', '-viewed_at'], name='analytics_b_user_id_4b559d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['-viewed_at'], name='analytics_b_viewed__46a32c_idx'),
        ),
    ]
