# Generated by Django 5.0.1 on 2026-01-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.blogcomment'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blogs.category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='blogs.tag'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blogs_blog_slug_d0bba8_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status'], name='blogs_blog_status_a241b2_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author'], name='blogs_blog_author__166d94_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-published_at'], name='blogs_blog_publish_49fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_featured'], name='blogs_blog_is_feat_cc1d4c_idx'),
        ),
    ]
